name: php

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  phpcs:
    runs-on: ubuntu-latest
  
    steps:
      - uses: actions/checkout@v2

      - uses: shivammathur/setup-php@v2
        with:
          php-version: '7.4'
          tools: composer

      - run: composer install

      - run: ./vendor/bin/phpcs --standard=./ruleset.xml

  phpunit:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        php-version: [7.4]

    services:
      mysql:
        image: mysql:5
        env:
          MYSQL_ROOT_PASSWORD: root-password
        ports:
          - 3306
        options: --health-cmd="mysqladmin ping" --health-interval=10s --health-timeout=5s --health-retries=3

    steps:
      - uses: actions/checkout@v2

      - uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php-version }}
          extensions: mysqli
          tools: composer
          coverage: xdebug

      - run: composer install

      - run: bin/install-wp-tests.sh test root root-password 127.0.0.1:${{ job.services.mysql.ports['3306'] }}
      - run: ./vendor/bin/phpunit
